updated -- frontend with nextjs

diff --git a/frontend/src/Dockerfile b/frontend/src/Dockerfile
--- a/frontend/src/Dockerfile
+++ b/frontend/src/Dockerfile
@@ -1,31 +1,57 @@
-# Use base golang image from Docker Hub
-FROM golang:latest as build
-
+FROM node:latest AS deps
+# RUN apk add --no-cache libc6-compat
 WORKDIR /app
+# COPY package.json yarn.lock* package-lock.json* ./
+EXPOSE 3000
+COPY package* ./
+RUN npm install --no-package-lock
+COPY . .
+CMD ["npm", "run", "dev"]
 
-# Copy the go.mod and go.sum, download the dependencies
-COPY go.mod go.sum ./
-RUN go mod download
+# RUN \
+#     if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+#     elif [ -f package-lock.json ]; then npm ci; \
+#     else echo "Lock file not found." && exit 1; \
+#     fi
 
-# Copy rest of the application source code
-COPY . ./
+# End (Block 1)
 
-# Compile the application to /app/frontend.
-# Skaffold passes in debug-oriented compiler flags
-ARG SKAFFOLD_GO_GCFLAGS
-RUN echo "Go gcflags: ${SKAFFOLD_GO_GCFLAGS}"
-RUN go build -gcflags="${SKAFFOLD_GO_GCFLAGS}" -mod=readonly -v -o /app/frontend .
+# Start (Block 2) Build the Application Stage
 
-# Now create separate deployment image
-FROM gcr.io/distroless/base
+# FROM node:latest AS builder
+# WORKDIR /app
 
-# Definition of this variable is used by 'skaffold debug' to identify a golang binary.
-# Default behavior - a failure prints a stack trace for the current goroutine.
-# See https://golang.org/pkg/runtime/
-ENV GOTRACEBACK=single
+# COPY --from=deps /app/node_modules ./node_modules
+# COPY . .
+# RUN yarn build
 
-WORKDIR /app
-COPY static /app/static
-COPY templates /app/templates
-COPY --from=build /app/frontend /app/frontend
-ENTRYPOINT ["/app/frontend"]
+# End (Block 2)
+
+# Start (Block 3) Create the Application Runner
+# FROM node:latest AS runner
+# WORKDIR /app
+
+# Declare the NODE_ENV
+# ENV NODE_ENV production
+
+# Add the Group and User to Container 
+# RUN addgroup --system --gid 1001 nodejs
+# RUN adduser --system --uid 1001 nextjs
+
+# Copy the next js application form builder image
+# COPY --from=builder /app/public ./public
+# COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
+# COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
+
+# USER nextjs
+# Expose the Application Port 
+# EXPOSE 3000
+# Add the Environment Port Variable
+# ENV PORT 3000
+# CMD ["npm", "run", "dev"]
+# COPY . .
+
+# Run the Application with "server.js" using node, which is 
+# Auto Generated by Standalone mode
+# CMD ["node", "server.js"]
+# End (Block 3)
